# Generated by Django 4.2.15 on 2025-01-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='inspiration',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
