# Generated by Django 4.2.15 on 2025-01-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_f6vj23.jpg', upload_to='images/'),
        ),
    ]
