# Generated by Django 4.2.15 on 2025-01-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppCategory',
            new_name='PostCategory',
        ),
    ]
