# Generated by Django 4.2.15 on 2025-01-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_appcategory_postcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
