# Generated by Django 4.2.15 on 2025-01-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_postcategory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ['name']},
        ),
    ]
