# Generated by Django 4.2.15 on 2024-11-11 02:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0005_category_alter_group_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='category',
            new_name='group_category',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(related_name='participation_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
