# Generated by Django 4.2.15 on 2024-11-11 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_rename_category_group_group_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_category',
            new_name='category',
        ),
    ]
